package handlers;

public enum MessageType {
    STRING,
    ARRAY_LIST_STRING,
    ARRAY_LIST_QUESTION,
    MAP_STRING_ARRAYLIST_STRING,
    MAP_STRING_STRING, 
    ARRAY_LIST_EXAM, 
    ARRAY_LIST_QUESTIONINEXAM,
    ARRAY_LIST_HOD,
    ARRAY_LIST_FINISHED_EXAM,
    ARRAY_LIST_STUDENT_GRADE
}
